# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06fe06e347d188ab0135f8bb59b282b29627884d8a0acb5ffd72e39b53ee6cbac77b68860cf85b40864aaa328e0e33b206d0df41ff19f330066a17694f9c72ec

test:
  secret_key_base: 73afedb1ff1c348d278312e8192651a5d2a98ce4e77bc01e89796f84baf8e68e08cd24d00161e7baea3f1cc16c0452fe2aed1784830481d2228bfd87692c9b14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
